import os.path

from build_utils.utils import build_lua_table
from scripts.build_utils.utils.tables.WoWTables import WowTablesCache

locales = {
    "enUS": "English (US)",
    "koKR": "Korean",
    "frFR": "French",
    "deDE": "German",
    "zhCN": "Simplified Chinese",
    "esES": "Spanish",
    "zhTW": "Taiwanese Mandarin",
    # "enGB": "English (GB)",
    "esMX": "Mexican Spanish",
    "ruRU": "Russian",
    "ptBR": "Brazilian Portugese",
    "itIT": "Italian",
    # "ptPT": "Portugese"
}

# Unlocalize diet and species

data = {}
for locale in locales.keys():
    tables = WowTablesCache(locale=locale, game='retail')
    table = tables.get_db_table('ItemPetFood')
    if locale == 'enUS':
        table_enus = dict(zip(map(lambda x: int(x['ID']), table), map(lambda x: x['Name_lang'], table)))
        continue

    for row in table:
        key = int(row['ID'])
        eng = table_enus[key]
        if locale not in data:
            data[locale] = {}
        data[locale][eng] = row['Name_lang']
        # data[locale][]

lua = build_lua_table(data, '_G.FOM_FoodLocale')
with open('../data/food_locale.lua', 'w', encoding='utf8') as fp:
    fp.write('--Generated by %s\n' % os.path.basename(__file__))
    fp.write(lua)
